package com.food.Online_Food_Ordering.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;


    @Entity
    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    public class OrderItem {

        @Id
        @GeneratedValue(strategy = GenerationType.AUTO)
        private Long id;

        @ManyToOne
        private Food food;

        private int quantity;

        private Long totalPrice;

        @ManyToMany(cascade = CascadeType.PERSIST)
        @JoinTable(
                name = "order_item_ingredients",
                joinColumns = @JoinColumn(name = "order_item_id"),
                inverseJoinColumns = @JoinColumn(name = "ingredients_item_id")
        )
        private List<IngredientsItem> ingredients;


        // Getters and setters (automatically generated by Lombok)


    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Food getFood() {
        return food;
    }

    public void setFood(Food food) {
        this.food = food;
    }

    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    public Long getTotalPrice() {
        return totalPrice;
    }

    public void setTotalPrice(Long totalPrice) {
        this.totalPrice = totalPrice;
    }

    public List<IngredientsItem> getIngredients() {
        return ingredients;
    }

    public void setIngredients(List<IngredientsItem> ingredients) {
        this.ingredients = ingredients;
    }
}
